// Generated by CoffeeScript 1.8.0
(function() {
  var A, B, a1, a2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  A = (function() {
    function A() {}

    A.prototype.name = "a";

    A.prototype.obj = {
      da: "la"
    };

    A.age = 4;

    return A;

  })();

  B = (function(_super) {
    __extends(B, _super);

    function B() {
      return B.__super__.constructor.apply(this, arguments);
    }

    return B;

  })(A);

  a1 = new A();

  a2 = new A();

  a1.obj.da = "changed";

  console.log(a2.obj.da);

}).call(this);
