// Generated by CoffeeScript 1.8.0
(function() {
  var arr, e, _i, _len;

  arr = [0, 1, 2];

  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    e = arr[_i];
    console.log(e);
  }

}).call(this);
