// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    Backbone.Events.on("laterEvents", function() {
      return console.log("get the event");
    });
    console.log("some initialization");
    return Backbone.Events.trigger("laterEvents");
  });

}).call(this);

//# sourceMappingURL=event.js.map
