// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(document).ready(function() {
    var Backpack, backpack;
    Backpack = (function(_super) {
      __extends(Backpack, _super);

      function Backpack() {
        return Backpack.__super__.constructor.apply(this, arguments);
      }

      Backpack.prototype.defaults = {
        name: "easy",
        age: 45
      };

      Backpack.prototype.initialize = function() {
        this.set({
          ids: [4, 5, 6]
        });
        this.on("change:ids", this.say);
        return this.on('change:name', this.name);
      };

      Backpack.prototype.say = function() {
        return console.log("ids has changed");
      };

      Backpack.prototype.name = function() {
        return console.log('name changed');
      };

      return Backpack;

    })(Backbone.Model);
    backpack = new Backpack();
    console.log(backpack.get('name'));
    backpack.set({
      'name': 'ok'
    });
    console.log(backpack.get('name'));
    backpack.set({
      'name': 'ok'
    });
    return console.log('anything happened?');
  });

}).call(this);

//# sourceMappingURL=nested.js.map
