// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(document).ready(function() {
    var Father, Son, son;
    Father = (function(_super) {
      __extends(Father, _super);

      function Father() {
        return Father.__super__.constructor.apply(this, arguments);
      }

      Father.prototype.initialize = function(name, second, sta) {
        return console.log(name, second, sta);
      };

      return Father;

    })(Backbone.Model);
    Son = (function(_super) {
      __extends(Son, _super);

      function Son() {
        return Son.__super__.constructor.apply(this, arguments);
      }

      Son.prototype.initialize = function(sta, name, second) {
        return Son.__super__.initialize.apply(this, arguments);
      };

      return Son;

    })(Father);
    return son = new Son("tony", "mom", "aha");
  });

}).call(this);

//# sourceMappingURL=super.js.map
